name: demo2-gin-frame
db:
  name: test
  host: 124.70.56.141:32250
  username: root
  password: 123456
  charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 2
redis:
  host: 124.70.56.141
  port: 32251
  auth:
mode: debug
addr: :8080
max_ping_count: 4
log:
  level: debug
  file_format: "%Y%m%d"
  max_save_days: 30
  file_type: one #one, level